Roguelike. Design Document
ekiuled/roguelike pull request #1
Opened 2021-04-04 20:50 UTC by ekiuled

2021-04-13 14:42 UTC, aleksZubakov requested changes

2021-04-13 14:42 UTC, aleksZubakov commented on Design Document.md
> +![Client-Server](docs/use_case2.png)
По-хорошему use-case диаграмма -- это про взоимодействие пользователя с нашей системой. 

У Вас тут скорее описание того как система работает (что делает клиентское приложение, а не сам пользователь), для этого что-то другое нужно рисовать, не use-case диаграмму. Либо sequence, либо вообще какой-нибудь конечный автомат рисовать.

2021-04-13 14:42 UTC, aleksZubakov commented on Design Document.md
> +![Player-Client](docs/use_case1.png)
Эта диаграмма в этом смысле адекватная

2021-04-13 14:42 UTC, aleksZubakov commented on Design Document.md
> +![Component diagram](docs/components.png)
Нахожу немного странным, что контроллер вынесен совсем на сервер. Если мы сервер захотим утащить на настоящий сервер, то отправлять пользовательский ввод куда-то вообще всегда кажется плохой идеей

2021-04-13 14:42 UTC, aleksZubakov commented on Design Document.md
> +![Classes diagram](docs/classes_model.png)
Грязноватая диаграмма получилась.

Плохо, что Map и Model болтаются без какого-либо адекватного интерфейса, они просто пустые. Если вы так хотели показать, что это часть компоненты, то лучше вообще их убрать. Если нет, то дополняйте. 

Название `Live` плохое для интерфейса. Можно не дублировать методы, если поле уже написано (я про changeHealth и setPosition/getPosition у `Entity`)

У `Mob` точно нет своих методов?

Ну и я бы все-таки попросил и другие компоненты тоже расписать, ну хотя бы половину из них.

2021-04-19 21:46 UTC, ekiuled commented
Мы исправили диаграммы компонентов и классов и добавили ещё одну диаграмму классов.

2021-04-21 13:24 UTC, aleksZubakov commented
Засчитываю

2021-04-23 16:50 UTC, merged