Roguelike. Поле и управление.
ekiuled/roguelike pull request #2
Opened 2021-04-19 00:05 UTC by ekiuled

2021-04-23 16:03 UTC, aleksZubakov requested changes
В целом, хорошо и аккуратно, поправьте замечания и добавьте комментарии и хоть какие-то тесты. Пока 8 из 10

2021-04-23 16:03 UTC, ottergottaott commented on client/src/main/java/roguelike/input/InputHandler.java
> +public class InputHandler extends KeyAdapter {
Код должен быть прокомментирован

2021-04-23 16:03 UTC, ottergottaott commented on client/src/main/java/roguelike/Client.java
> +        UI ui = new UI(new ServerConnection(username));
неиспользуемая переменная

2021-04-23 16:03 UTC, ottergottaott commented on server/src/main/java/roguelike/controller/Controller.java
> +                false,
Оверинжениринг, конечно, но похвально, что rabbitmq используете.

Сможете пояснить почему очереди не durable сделаны? Это осмысленное что-то или наугад?

2021-04-23 16:03 UTC, ottergottaott commented on server/src/main/java/roguelike/controller/Controller.java
> +        });
Кажется, что не очень хорошо `cancelCallback` пустым оставлять

2021-04-23 16:03 UTC, ottergottaott commented on server/src/main/java/roguelike/controller/Controller.java
> +        });
Еще кажется, что возврааемый tag может понадобиться, нет?

2021-04-23 16:03 UTC, ottergottaott commented on server/src/main/java/roguelike/model/Level.java
> +    private Map<UUID, Mob> mobs;
Кажется, что это тоже может быть final

2021-04-23 16:03 UTC, ottergottaott commented on server/src/main/java/roguelike/model/Level.java
> +        mobs = new HashMap<>();
Если вот тут дописать метод и не создавать mobs заново, а по-честному наполнять, то точно final будет

2021-04-23 16:03 UTC, ottergottaott commented on client/src/main/java/roguelike/ui/UI.java
> +                    serverConnection.sendAction(Action.EXIT);
Вот тут дискуссионный момент: я не уверен, что хорошо идея именно на UI вешать подбирание ресурсов. Чревато тем, что
а) ресурсов может стать больше, но как-то странно лезть в код ui каждый раз
б) сейчас при закрытии UI будет висеть (и очень сильно бесить пользователя) до момента, пока коннекшн не дропнется, а так бы закрылись уже спокойно и процесс где-то в фоне спокойно бы дождался и помер.

Исправлять не нужно сейчас, т.к. в данной ситуации это сложно как-то еще сделать, но обязательно подумайте как можно было бы исправить

2021-04-23 16:03 UTC, ottergottaott commented on lib/src/main/java/roguelike/util/ControlMessage.java
> +public class ControlMessage {
Вот тут еще наверняка появятся параметры, одним `Action` точно не обойдется

2021-04-23 16:04 UTC, aleksZubakov commented
@EliseevEgor поработайте еще над сообщениями к коммитам, `fixes1`, `fixes2` и подобное -- плохо

2021-04-24 17:35 UTC, ekiuled commented on server/src/main/java/roguelike/controller/Controller.java
> +                false,
Это наугад. Сейчас посмотрела в документацию очередей, написано, что по умолчанию лучше делать durable. На самом деле не понятно, нужно ли нам это: если игра запущена, а брокер вдруг решил перезапуститься, то игра упадёт и правильно сделает. Как я поняла, именно в этом случае будут восстановлены durable очереди. 

Вот параметр autoDelete нужен, я его установила сейчас.

2021-04-24 18:05 UTC, ekiuled commented on server/src/main/java/roguelike/controller/Controller.java
> +        });
Tag вроде не нужен, отменять consumer'а через него мы не собираемся.

2021-05-01 18:11 UTC, ekiuled commented
Мы поправили код и добавили комментариев и немного тестов.

2021-05-14 17:06 UTC, aleksZubakov commented
Оке, засчитываю

На всякий напоминаю, что работа командная и исправления по-хорошему тоже оба должны делать, комментарии добавить хорошо, но код тоже писать стоит :)

2021-05-14 17:14 UTC, merged