Задача Roguelike. Боевая система.
ekiuled/roguelike pull request #3
Opened 2021-04-26 01:57 UTC by ekiuled

2021-05-14 17:37 UTC, aleksZubakov requested changes
Более-менее ок. 

Было бы хорошо как-то сообщать клиенту, что он наигрался и помер, а то сейчас все просто останавливается и больше похоже на зависание, чем нет :)

7 баллов

2021-05-14 17:37 UTC, aleksZubakov commented on server/src/main/java/roguelike/view/View.java
> +        Collection<Mob> mobs = newLevel.getMobs().values();
Вот этих ребят поближе бы к местам использования, тут им делать явно нечего

2021-05-14 17:37 UTC, aleksZubakov commented on server/src/main/java/roguelike/mobAI/NeutralAI.java
> +        if (Math.random() > 0.7) {
Вероятности я бы повыносил, чтобы потом проще было менять/добавлять конфиг

Условную сложность можно так настроить -- условный геймдизайнер так сможет легче потестить кучу вариантов об игроков

2021-05-14 17:37 UTC, aleksZubakov commented on server/src/main/java/roguelike/mobAI/MobsAI.java
> +            } catch (InterruptedException ignored) {
А-та-та, конечно. Хотя бы [вот так](https://stackoverflow.com/questions/1087475/when-does-javas-thread-sleep-throw-interruptedexception)

2021-05-14 17:37 UTC, aleksZubakov commented on server/src/main/java/roguelike/mobAI/MobsAI.java
> +                Thread.sleep(Math.max(0, frame_interval_ms - durationMs));
А вообще это же всю игру отправит спать, это нормально?

2021-05-14 17:37 UTC, aleksZubakov commented on server/src/main/java/roguelike/mobAI/MobAI.java
> +        int x0 = mob.getPosition().getX();
Этот код дублируется в других мобах

2021-05-14 20:01 UTC, aleksZubakov commented on server/src/main/java/roguelike/mobAI/MobAI.java
> +    protected abstract Action generateAction();
Ага, в задании еще вот это было:

> Используйте паттерн стратегия

2021-05-17 19:59 UTC, EliseevEgor commented on server/src/main/java/roguelike/mobAI/MobAI.java
> +    protected abstract Action generateAction();
> Ага, в задании еще вот это было:
> 
> > Использовать паттерн стратегия

Здравствуйте @aleksZubakov, а можно спросить, пожалуйста, что имеется ввиду?
Вроде у нас есть одна функция и несколько её разных реализаций. В зависимости от моба, мы выбираем нужную нам стратегию его поведения.

2021-05-17 22:53 UTC, ekiuled commented on server/src/main/java/roguelike/mobAI/MobsAI.java
> +                Thread.sleep(Math.max(0, frame_interval_ms - durationMs));
Уснёт только поток с MobsAI, а обработка сообщений от игроков и мобов (собственно, игра) происходит в хендлере, который RabbitMQ запускает в отдельном потоке.

2021-05-25 15:27 UTC, aleksZubakov commented on server/src/main/java/roguelike/mobAI/MobAI.java
> +    protected abstract Action generateAction();
Имеется ввиду вот [это](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F))

Логика примерно такая: у нас есть какой-то класс, который будет использовать стратегии (на вики это `Context`). Код основной программы понятия не имеет какие стратегии бывают в том смысле, что он никак не использует их потенциальное содержиоме и пр., но может звать `Context`. При этом в сам контекст мы можем положить стратегию при его создании и/или позднее ее поменять.

Вы же сейчас по сути работаете с обычными наследниками, пусть и спрятав их в `MobsAI`, поменять стратегию никак нельзя, нужно идти и пересоздавать моба целиком. 

Тоже самое, но с вики:
> - Программа должна обеспечивать различные варианты алгоритма или поведения
> - Нужно изменять поведение каждого экземпляра класса
> - Необходимо изменять поведение объектов на стадии выполнения 
> - Введение интерфейса позволяет классам-клиентам ничего не знать о классах, реализующих этот интерфейс и инкапсулирующих в себе конкретные алгоритмы

В нашем задании это особо не используется дальше, но представьте, что на моба можно наложить пассивный баф, он от него внезапно вместо агрессивного превращается в трусливого,

2021-05-25 17:45 UTC, aleksZubakov commented
В целом, ок засчитываю

2021-05-29 21:36 UTC, merged